include:
  - "/gitlab-ci/stages.yml"
  - "/gitlab-ci/common.yml"

# =============================================================================
# CLIENT SUBPROJECT
# =============================================================================

build and test client:
  stage: build and test
  interruptible: true
  script:
    - !reference [.build_shared_types, script]
    - cd client
    - !reference [.use_nvm, script]
    - yarn lint-strict
    - yarn test
    - export NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY_DEVELOPMENT
    - yarn build
  artifacts:
    paths:
      - client/.next
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - client/**/*
        - gitlab-ci/stages/01-build-and-test.yml
    - !reference [.rules, on_merge_to_master]
    - !reference [.rules, on_merge_to_prod]

build client docker image for test:
  stage: build and test
  extends:
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  artifacts:
    paths:
      - client/image-test.tar
    expire_in: 1 hour
  script:
    - BUILD_VERSION=`date +%y.%m.%d.%H.%M.$CI_COMMIT_SHORT_SHA`
    - echo "Labelling this build as $BUILD_VERSION"
    # Environment-specific .env flags are set here.
    # Service-type flags are set in terraform on launch.
    - >
      docker build
      --build-arg APP_ENV=test
      --build-arg BUILD_VERSION="${BUILD_VERSION}"
      --build-arg CLERK_PUBLISHABLE_KEY="${CLERK_PUBLISHABLE_KEY_DEVELOPMENT}"
      --build-arg NEXT_PUBLIC_POSTHOG_KEY="${POSTHOG_KEY_DEVELOPMENT}"
      --build-arg NEXT_PUBLIC_POSTHOG_HOST="https://us.i.posthog.com"
      --build-arg NEXT_PUBLIC_API_URL=https://test-api.scratch.md
      --build-arg NEXT_PUBLIC_AI_AGENT_WEBSOCKET_URL=wss://test-agent.scratch.md
      --build-arg NEXT_PUBLIC_AI_AGENT_API_URL=https://test-agent.scratch.md
      --build-arg POSTHOG_PROJECT_ID="${POSTHOG_PROJECT_ID_TEST}"
      --build-arg POSTHOG_CLI_API_KEY="${POSTHOG_CLI_API_KEY_TEST}"
      -t spinner/spinner-client-test
      -f client/Dockerfile.monorepo .
    - docker save spinner/spinner-client-test > client/image-test.tar
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - client/Dockerfile.monorepo
        - client/package.json
        - gitlab-ci/stages/01-build-and-test.yml
        - gitlab-ci/stages/03-push-images.yml
    - !reference [.rules, on_merge_to_master]

build client docker image for production:
  stage: build and test
  extends:
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  artifacts:
    paths:
      - client/image-production.tar
    expire_in: 1 hour
  script:
    - BUILD_VERSION=`date +%y.%m.%d.%H.%M.$CI_COMMIT_SHORT_SHA`
    - echo "Labelling this build as $BUILD_VERSION"
    # Environment-specific .env flags are set here.
    # Service-type flags are set in terraform on launch.
    - >
      docker build
      --build-arg APP_ENV=production
      --build-arg BUILD_VERSION="${BUILD_VERSION}"
      --build-arg CLERK_PUBLISHABLE_KEY="${CLERK_PUBLISHABLE_KEY_PRODUCTION}"
      --build-arg NEXT_PUBLIC_POSTHOG_KEY="${POSTHOG_KEY}"
      --build-arg NEXT_PUBLIC_POSTHOG_HOST="https://us.i.posthog.com"
      --build-arg NEXT_PUBLIC_API_URL=https://api.scratch.md
      --build-arg NEXT_PUBLIC_AI_AGENT_WEBSOCKET_URL=wss://agent.scratch.md
      --build-arg NEXT_PUBLIC_AI_AGENT_API_URL=https://agent.scratch.md
      --build-arg NEXT_PUBLIC_GA_ID=G-GVXSMCZ3JR
      --build-arg POSTHOG_PROJECT_ID="${POSTHOG_PROJECT_ID_PRODUCTION}"
      --build-arg POSTHOG_API_KEY="${POSTHOG_CLI_API_KEY_PRODUCTION}"
      -t spinner/spinner-client-production
      -f client/Dockerfile.monorepo .
    - docker save spinner/spinner-client-production > client/image-production.tar
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - client/Dockerfile.monorepo
        - client/package.json
        - gitlab-ci/stages/01-build-and-test.yml
        - gitlab-ci/stages/03-push-images.yml
    - !reference [.rules, on_merge_to_prod]

# =============================================================================
# SERVER SUBPROJECT
# =============================================================================

build and test server:
  stage: build and test
  interruptible: true
  script:
    - !reference [.build_shared_types, script]
    - cd server
    - !reference [.use_nvm, script]
    - yarn lint-strict
    - yarn test
    - BUILD_VERSION=`date +%y.%m.%d.%H.%M.$CI_COMMIT_SHORT_SHA`
    - echo "export const BUILD_VERSION = '$BUILD_VERSION';" > src/version.ts
    - echo "Labelling this build as $BUILD_VERSION"
    - yarn build
  artifacts:
    paths:
      - server/dist
    expire_in: 1 hour
  cache: !reference [.caches, server]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - server/**/*
        - gitlab-ci/stages/01-build-and-test.yml
    - !reference [.rules, on_merge_to_master]
    - !reference [.rules, on_merge_to_prod]

build server docker image:
  stage: build and test
  extends:
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  artifacts:
    paths:
      - server/image.tar
    expire_in: 1 hour
  script:
    - BUILD_VERSION=`date +%y.%m.%d.%H.%M.$CI_COMMIT_SHORT_SHA`
    - echo "Labelling this build as $BUILD_VERSION"
    - >
      docker build
      --build-arg BUILD_VERSION="${BUILD_VERSION}"
      -t spinner/spinner-server
      -f server/Dockerfile.monorepo .
    - docker save spinner/spinner-server > server/image.tar
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - server/Dockerfile
        - server/package.json
        - gitlab-ci/stages/01-build-and-test.yml
        - gitlab-ci/stages/03-push-images.yml
    - !reference [.rules, on_merge_to_master]
    - !reference [.rules, on_merge_to_prod]

# =============================================================================
# PYDANTIC-AI-AGENT SUBPROJECT
# =============================================================================

build and test agent:
  stage: build and test
  image: python:$PYTHON_VERSION-slim
  script:
    - cd pydantic-ai-agent
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Checking for Python syntax errors"
    - find . -name "*.py" -not -path "./venv/*" -not -path "./testing/*" -print -exec python -m py_compile {} \;
    - echo "Checking for Python code style issues"
    - black --check .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - pydantic-ai-agent/**/*
        - gitlab-ci/stages/01-build-and-test.yml
    - !reference [.rules, on_merge_to_master]
    - !reference [.rules, on_merge_to_prod]

build agent docker image:
  stage: build and test
  extends:
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  artifacts:
    paths:
      - pydantic-ai-agent/image.tar
    expire_in: 1 hour
  script:
    - cd pydantic-ai-agent
    - BUILD_VERSION=`date +%y.%m.%d.%H.%M.$CI_COMMIT_SHORT_SHA`
    - echo "Labelling this build as $BUILD_VERSION"
    - >
      docker build
      --build-arg BUILD_VERSION="${BUILD_VERSION}"
      -t spinner/spinner-agent
      -f Dockerfile .
    - docker save spinner/spinner-agent > image.tar
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - pydantic-ai-agent/Dockerfile
        - pydantic-ai-agent/package.json
        - gitlab-ci/stages/01-build-and-test.yml
        - gitlab-ci/stages/03-push-images.yml
    - !reference [.rules, on_merge_to_master]
    - !reference [.rules, on_merge_to_prod]

# =============================================================================
# MISC
# =============================================================================

dummy job:
  stage: build and test
  interruptible: true
  image:
  script:
    - echo "Gitlab won't merge a MR with changes only in these directories, since that doesn't trigger any pipelines"
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_PIPELINE_SOURCE != "schedule"'
      changes:
        - terraform/**/*
        - .cursor/**/*
        - gitlab-ci/**/*
        - mcp/**/*
        - .vscode/**/*
        - experimental/**/*
        - "*"
