include:
  - "/gitlab-ci/stages.yml"
  - "/gitlab-ci/common.yml"

# =============================================================================
# CLIENT SUBPROJECT
# =============================================================================

build and test client:
  stage: build
  image: node:$NODE_VERSION
  interruptible: true
  script:
    - cd client
    - yarn install --frozen-lockfile
    - yarn lint-strict
    - export NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY_DEVELOPMENT
    - yarn build
  artifacts:
    paths:
      - client/.next
    expire_in: 1 hour
  only:
    changes:
      - client/**/*
    refs:
      - merge_requests
      - master

# =============================================================================
# SERVER SUBPROJECT
# =============================================================================

build and test server:
  stage: build
  image: node:$NODE_VERSION
  interruptible: true
  script:
    - cd server
    - yarn install --frozen-lockfile
    - yarn prisma generate
    - yarn lint
    - yarn test
    - BUILD_VERSION=`date +%y.%m.%d.%H.%M.$CI_COMMIT_SHORT_SHA`
    - echo "export const BUILD_VERSION = '$BUILD_VERSION';" > src/version.ts
    - echo "Labelling this build as $BUILD_VERSION"
    - yarn build
  artifacts:
    paths:
      - server/dist
    expire_in: 1 hour
  only:
    changes:
      - server/**/*
    refs:
      - merge_requests
      - master

# TODO: convert this to a Gitlab "Step":
# https://docs.gitlab.com/tutorials/setup_steps/
#
# this builds one docker image for all of the bottlenose variants for the test environment.
# note: this contrasts with the aws variants that build one for each environment.
# at runtime, the image needs to be provided with service_type and friendly_service_name vars.
gcp push test server image to artifact registry:
  stage: build
  needs:
    - job: build and test server
      artifacts: true
  extends:
    - .gcp_test_env # sets before_script and variables
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  script:
    - !reference [.setup_docker_gcp_auth, script]
    - cd server
    # Environment-specific .env flags are set here.
    # Service-type flags are set in terraform on launch.
    - >
      docker build
      -t spinner-test/spinner-server
      -f Dockerfile .
    # Push twice, tagged as both 'latest' and '$CI_COMMIT_SHORT_SHA'
    - docker tag spinner-test/spinner-server:latest ${GCP_REGISTRY_URL}/spinner-server:$CI_COMMIT_SHORT_SHA
    - docker push ${GCP_REGISTRY_URL}/spinner-server:$CI_COMMIT_SHORT_SHA
    - docker tag spinner-test/spinner-server:latest ${GCP_REGISTRY_URL}/spinner-server:latest
    - docker push ${GCP_REGISTRY_URL}/spinner-server:latest
  only:
    refs:
      - master
      - staging
      - prod

# =============================================================================
# PYDANTIC-AI-AGENT SUBPROJECT
# =============================================================================

build and test agent:
  stage: build
  image: python:$PYTHON_VERSION-slim
  script:
    - cd pydantic-ai-agent
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Checking for Python syntax errors"
    - find . -name "*.py" -not -path "./venv/*" -not -path "./testing/*" -print -exec python -m py_compile {} \;
    - echo "Checking for Python code style issues"
    - black --check .
  only:
    changes:
      - pydantic-ai-agent/**/*
    refs:
      - merge_requests
      - master
