include:
  - "/gitlab-ci/stages.yml"
  - "/gitlab-ci/common.yml"

# =============================================================================
# CLIENT SUBPROJECT
# =============================================================================

build and test client:
  stage: build
  image: node:$NODE_VERSION
  interruptible: true
  script:
    - cd client
    - yarn install --frozen-lockfile
    - yarn lint-strict
    - export NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY_DEVELOPMENT
    - yarn build
  artifacts:
    paths:
      - client/.next
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - client/**/*
    - !reference [.rules, on_merge_to_master]
    - !reference [.rules, on_merge_to_prod]

gcp push test client image to artifact registry:
  stage: build
  needs:
    - job: build and test client
      artifacts: true
  extends:
    - .gcp_test_env # sets before_script and variables
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  script:
    - !reference [.setup_docker_gcp_auth, script]
    - cd client
    - BUILD_VERSION=`date +%y.%m.%d.%H.%M.$CI_COMMIT_SHORT_SHA`
    - echo "Labelling this build as $BUILD_VERSION"
    # Environment-specific .env flags are set here.
    # Service-type flags are set in terraform on launch.
    - >
      docker build
      --build-arg APP_ENV=test
      --build-arg BUILD_VERSION="${BUILD_VERSION}"
      --build-arg CLERK_PUBLISHABLE_KEY="${CLERK_PUBLISHABLE_KEY_PRODUCTION}"
      --build-arg NEXT_PUBLIC_POSTHOG_KEY="${POSTHOG_KEY}"
      --build-arg NEXT_PUBLIC_POSTHOG_HOST="https://us.i.posthog.com"
      --build-arg NEXT_PUBLIC_API_URL=https://api.scratchpaper.ai
      --build-arg NEXT_PUBLIC_AI_AGENT_WEBSOCKET_URL=wss://agent.scratchpaper.ai
      --build-arg NEXT_PUBLIC_AI_AGENT_API_URL=https://agent.scratchpaper.ai
      -t spinner-test/spinner-client
      -f Dockerfile .
    # Push twice, tagged as both 'latest' and '$CI_COMMIT_SHORT_SHA'
    - docker tag spinner-test/spinner-client:latest ${GCP_REGISTRY_URL}/spinner-client:$CI_COMMIT_SHORT_SHA
    - docker push ${GCP_REGISTRY_URL}/spinner-client:$CI_COMMIT_SHORT_SHA
    - docker tag spinner-test/spinner-client:latest ${GCP_REGISTRY_URL}/spinner-client:latest
    - docker push ${GCP_REGISTRY_URL}/spinner-client:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - client/Dockerfile
        - client/package.json
    - !reference [.rules, on_merge_to_master]
    - !reference [.rules, on_merge_to_prod]

# =============================================================================
# SERVER SUBPROJECT
# =============================================================================

build and test server:
  stage: build
  image: node:$NODE_VERSION
  interruptible: true
  script:
    - cd server
    - yarn install --frozen-lockfile
    - yarn prisma generate
    - yarn lint
    - yarn test
    - BUILD_VERSION=`date +%y.%m.%d.%H.%M.$CI_COMMIT_SHORT_SHA`
    - echo "export const BUILD_VERSION = '$BUILD_VERSION';" > src/version.ts
    - echo "Labelling this build as $BUILD_VERSION"
    - yarn build
  artifacts:
    paths:
      - server/dist
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - server/**/*
    - !reference [.rules, on_merge_to_master]
    - !reference [.rules, on_merge_to_prod]

# TODO: convert this to a Gitlab "Step":
# https://docs.gitlab.com/tutorials/setup_steps/
gcp push test server image to artifact registry:
  stage: build
  needs:
    - job: build and test server
      artifacts: true
  extends:
    - .gcp_test_env # sets before_script and variables
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  script:
    - !reference [.setup_docker_gcp_auth, script]
    - cd server
    # Environment-specific .env flags are set here.
    # Service-type flags are set in terraform on launch.
    - >
      docker build
      -t spinner-test/spinner-server
      -f Dockerfile .
    # Push twice, tagged as both 'latest' and '$CI_COMMIT_SHORT_SHA'
    - docker tag spinner-test/spinner-server:latest ${GCP_REGISTRY_URL}/spinner-server:$CI_COMMIT_SHORT_SHA
    - docker push ${GCP_REGISTRY_URL}/spinner-server:$CI_COMMIT_SHORT_SHA
    - docker tag spinner-test/spinner-server:latest ${GCP_REGISTRY_URL}/spinner-server:latest
    - docker push ${GCP_REGISTRY_URL}/spinner-server:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - server/Dockerfile
        - server/package.json
    - !reference [.rules, on_merge_to_master]
    - !reference [.rules, on_merge_to_prod]

# =============================================================================
# PYDANTIC-AI-AGENT SUBPROJECT
# =============================================================================

build and test agent:
  stage: build
  image: python:$PYTHON_VERSION-slim
  script:
    - cd pydantic-ai-agent
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Checking for Python syntax errors"
    - find . -name "*.py" -not -path "./venv/*" -not -path "./testing/*" -print -exec python -m py_compile {} \;
    - echo "Checking for Python code style issues"
    - black --check .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - pydantic-ai-agent/**/*
    - !reference [.rules, on_merge_to_master]
    - !reference [.rules, on_merge_to_prod]

gcp push test agent image to artifact registry:
  stage: build
  needs:
    - job: build and test agent
      artifacts: true
  extends:
    - .gcp_test_env # sets before_script and variables
    - .docker_builder_image
  cache: []
  services:
    - docker:26-dind
  script:
    - !reference [.setup_docker_gcp_auth, script]
    - cd pydantic-ai-agent
    # Environment-specific .env flags are set here.
    # Service-type flags are set in terraform on launch.
    - >
      docker build
      -t spinner-test/spinner-agent
      -f Dockerfile .
    # Push twice, tagged as both 'latest' and '$CI_COMMIT_SHORT_SHA'
    - docker tag spinner-test/spinner-agent:latest ${GCP_REGISTRY_URL}/spinner-agent:$CI_COMMIT_SHORT_SHA
    - docker push ${GCP_REGISTRY_URL}/spinner-agent:$CI_COMMIT_SHORT_SHA
    - docker tag spinner-test/spinner-agent:latest ${GCP_REGISTRY_URL}/spinner-agent:latest
    - docker push ${GCP_REGISTRY_URL}/spinner-agent:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - pydantic-ai-agent/Dockerfile
        - pydantic-ai-agent/requirements.txt
    - !reference [.rules, on_merge_to_master]
    - !reference [.rules, on_merge_to_prod]
