include:
  - "/gitlab-ci/stages.yml"
  - "/gitlab-ci/common.yml"

# NOTE: this doesn't work yet
push master to prod:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git config user.email "team+ci-bot@whalesync.com"
    - git config user.name "ci-bot"
    - git remote set-url origin https://oauth2:$CICD_ACCESS_TOKEN@gitlab.com/whalesync/spinner.git
    - git fetch --all --prune
    - git checkout master
    - git pull
    - git checkout prod
    - git pull origin prod
    - git merge -m "(Auto) Merge branch 'master' into prod" --no-ff -X theirs master
    - git push origin prod
    - echo "Successfully merged master into prod"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "schedule" && $PIPELINE_NAME == "AUTO_PUSH_PROD"'
