include:
  - "/gitlab-ci/stages.yml"
  - "/gitlab-ci/common.yml"

# =============================================================================
# INTEGRATION TESTS
# =============================================================================

integration tests for test env post-deploy:
  stage: post-deploy integration tests
  interruptible: false
  variables:
    CLERK_SECRET_KEY: "${CLERK_SECRET_KEY_DEVELOPMENT}"
    INTEGRATION_TEST_CLIENT_DOMAIN: "test.scratch.md"
    INTEGRATION_TEST_API_DOMAIN: "test-api.scratch.md"
    INTEGRATION_TEST_AGENT_DOMAIN: "test-agent.scratch.md"
    INTEGRATION_TEST_USER_ID: user_35RRk1ww8PJ4g0TfVfxbeU5iFJz
  script:
    - cd server
    - !reference [.use_nvm, script]
    - yarn run test:integration --verbose
  cache: !reference [.caches, server]
  rules:
    - !reference [.rules, on_merge_to_master]

integration tests for test env pre-deploy:
  stage: pre-deploy integration tests
  interruptible: false
  variables:
    CLERK_SECRET_KEY: "${CLERK_SECRET_KEY_DEVELOPMENT}"
    INTEGRATION_TEST_CLIENT_DOMAIN: "test.scratch.md"
    INTEGRATION_TEST_API_DOMAIN: "test-api.scratch.md"
    INTEGRATION_TEST_AGENT_DOMAIN: "test-agent.scratch.md"
    INTEGRATION_TEST_USER_ID: user_35RRk1ww8PJ4g0TfVfxbeU5iFJz
  script:
    - cd server
    - !reference [.use_nvm, script]
    - yarn run test:integration --verbose
  cache: !reference [.caches, server]
  rules:
    - !reference [.rules, on_merge_to_prod]

notify slack on integration test failure test env post-deploy:
  stage: post-deploy integration tests
  needs:
    - integration tests for test env post-deploy
  script:
    - |
      curl -X POST -H 'Content-type: application/json' \
      --data "{\"text\":\"❌ Integration tests for Scratch failed - Test\n<${CI_PIPELINE_URL}|View Pipeline>\"}" \
      ${SLACK_WEBHOOK_URL}
  rules:
    - !reference [.rules, on_merge_to_master]
  when: on_failure

notify slack on integration test failure test env pre-deploy:
  stage: pre-deploy integration tests
  needs:
    - integration tests for test env pre-deploy
  script:
    - |
      curl -X POST -H 'Content-type: application/json' \
      --data "{\"text\":\"❌ Integration tests for Scratch failed - Test\n<${CI_PIPELINE_URL}|View Pipeline>\"}" \
      ${SLACK_WEBHOOK_URL}
  rules:
    - !reference [.rules, on_merge_to_prod]
  when: on_failure
