include:
  - "/gitlab-ci/stages.yml"
  - "/gitlab-ci/common.yml"

# =============================================================================
# INTEGRATION TESTS
# =============================================================================

integration tests for test env:
  stage: integration tests
  interruptible: false
  variables:
    CLERK_SECRET_KEY: "${CLERK_SECRET_KEY_DEVELOPMENT}"
    INTEGRATION_TEST_CLIENT_DOMAIN: "test.scratch.md"
    INTEGRATION_TEST_API_DOMAIN: "test-api.scratch.md"
    INTEGRATION_TEST_AGENT_DOMAIN: "test-agent.scratch.md"
    INTEGRATION_TEST_USER_ID: user_35ABccxgr1W3QQoWiQ3ZhSzJg6g
  script:
    - cd server
    - !reference [.use_nvm, script]
    - yarn run test:integration --verbose
  cache: !reference [.caches, server]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - server/test/integration/**/*
        - gitlab-ci/stages/06-integration-tests.yml
    - !reference [.rules, on_merge_to_master]
