# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: scratchmd

before:
  hooks:
    - go mod tidy

builds:
  # Production build - points to production server
  - id: scratchmd-production
    main: ./cmd/scratchmd
    binary: scratchmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/whalesync/scratch-cli/internal/cmd.version={{.Version}}
      - -X github.com/whalesync/scratch-cli/internal/cmd.commit={{.Commit}}
      - -X github.com/whalesync/scratch-cli/internal/cmd.buildDate={{.Date}}
      - -X github.com/whalesync/scratch-cli/internal/api.DefaultScratchServerURL=https://api.scratch.md

  # Test build - points to test/staging server
  - id: scratchmd-test
    main: ./cmd/scratchmd
    binary: scratchmd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/whalesync/scratch-cli/internal/cmd.version={{.Version}}-test
      - -X github.com/whalesync/scratch-cli/internal/cmd.commit={{.Commit}}
      - -X github.com/whalesync/scratch-cli/internal/cmd.buildDate={{.Date}}
      - -X github.com/whalesync/scratch-cli/internal/api.DefaultScratchServerURL=https://test-api.scratch.md

archives:
  # Production archives
  - id: scratchmd-production
    ids:
      - scratchmd-production
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}

  # Test archives - with "-test" suffix
  - id: scratchmd-test
    ids:
      - scratchmd-test
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}-test_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true

release:
  github:
    owner: whalesync
    name: scratch-cli
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  # Do not upload source code archives

brews:
  - name: scratchmd
    ids:
      - scratchmd-production
    repository:
      owner: whalesync
      name: homebrew-scratch-cli
    # Use the release with the binaries
    url_template: "https://github.com/whalesync/scratch-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: whalesync-bot
      email: ci@whalesync.com
    homepage: "https://github.com/whalesync/scratch-cli"
    description: "Sync local Markdown files with your CMS (Webflow, WordPress, etc)."
    test: |
      system "#{bin}/scratchmd --version"

scoops:
  - repository:
      owner: whalesync
      name: scratch-cli-bucket
    ids:
      - scratchmd-production
    commit_author:
      name: whalesync-bot
      email: ci@whalesync.com
    homepage: "https://github.com/whalesync/scratch-cli"
    description: "Sync local Markdown files with your CMS."
    license: "Proprietary"

source:
  enabled: false
