variables:
  # Node.js version for client and server
  NODE_VERSION: "22"
  # Python version for pydantic-ai-agent
  PYTHON_VERSION: "3.12"
  # For GCP.
  GCP_REGION: "us-central1"

# default image used by all jobs unless overridden
image:
  name: unawareguitar/leaning-basket:08dd8de0
  #pull_policy: if-not-present

.docker_builder_image:
  image:
    name: unawareguitar/aws-dind:08dd8de0
    #pull_policy: if-not-present

# Any step can fetch GCP creds by extending from this rule.
# It will automatically fetch creds via OIDC and make them available as Application Default Credentials (ADC).
# Just add: extends: .google-oidc:auth
# NOTE! This breaks if you add a before_step to the step, since that clobbers the added work the rule adds.
include:
  - remote: "https://gitlab.com/gitlab-com/gl-security/security-operations/infrastructure-security-public/oidc-modules/-/raw/3.2.0/templates/gcp_auth.yaml"

.setup_docker_gcp_auth:
  script:
    - gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${GCP_REGION}-docker.pkg.dev

.use_nvm:
  script:
    # To get nvm working.
    - . ~/.bashrc
    - if [ ! -d node_modules ]; then nvm use && yarn install --immutable --cache-folder .yarn --prefer-offline; else echo "node_modules exists. Using cache."; fi

# Reusable snippet for including into rules to trigger jobs only on merge to master, not in MRs or scheduled pipelines
.rules:
  on_merge_to_master:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_PIPELINE_SOURCE != "schedule"'
  on_merge_to_prod:
    - if: '$CI_COMMIT_BRANCH == "prod" && $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_PIPELINE_SOURCE != "schedule"'

# Extend this rule to include OIDC auth and all required settings for the test project
.gcp_test_env:
  extends: .google-oidc:auth
  variables:
    TF_ROOT: "${CI_PROJECT_DIR}/terraform/envs/test"
    AUDIENCE: "https://gitlab.com"
  before_script:
    - export GCP_OIDC_JWT_ORIG=$GCP_OIDC_JWT
    - export GCLOUD_PROJECT="spv1-test"
    - export GCP_PROJECT_NUMBER="211553068097"
    - export CLOUDSDK_RUN_REGION="${GCP_REGION}"
    - export GCP_REGISTRY="test-registry"
    - export SERVICE_ACCOUNT="gitlab-service-account@spv1-test.iam.gserviceaccount.com"
    - export WI_POOL_PROVIDER="//iam.googleapis.com/projects/${GCP_PROJECT_NUMBER}/locations/global/workloadIdentityPools/gitlab-oidc-pool/providers/gitlab-oidc-provider"
    - export GCP_REGISTRY_URL="${GCP_REGION}-docker.pkg.dev/${GCLOUD_PROJECT}/${GCP_REGISTRY}"
    - export TF_ROOT="${CI_PROJECT_DIR}/terraform/envs/test"
    - !reference [.google-oidc:auth, before_script]

# Extend this rule to include OIDC auth and all required settings for the production project
.gcp_production_env:
  extends: .google-oidc:auth
  variables:
    TF_ROOT: "${CI_PROJECT_DIR}/terraform/envs/production"
    AUDIENCE: "https://gitlab.com"
  before_script:
    - export GCP_OIDC_JWT_ORIG=$GCP_OIDC_JWT
    - export GCLOUD_PROJECT="spv1-production"
    - export GCP_PROJECT_NUMBER="806617013435"
    - export CLOUDSDK_RUN_REGION="${GCP_REGION}"
    - export GCP_REGISTRY="production-registry"
    - export SERVICE_ACCOUNT="gitlab-service-account@spv1-production.iam.gserviceaccount.com"
    - export WI_POOL_PROVIDER="//iam.googleapis.com/projects/${GCP_PROJECT_NUMBER}/locations/global/workloadIdentityPools/gitlab-oidc-pool/providers/gitlab-oidc-provider"
    - export GCP_REGISTRY_URL="${GCP_REGION}-docker.pkg.dev/${GCLOUD_PROJECT}/${GCP_REGISTRY}"
    - export TF_ROOT="${CI_PROJECT_DIR}/terraform/envs/production"
    - !reference [.google-oidc:auth, before_script]

.caches:
  server:
    key:
      files:
        - server/yarn.lock
    paths:
      - server/node_modules
    unprotect: true
  client:
    key:
      files:
        - client/yarn.lock
    paths:
      - client/node_modules
    unprotect: true
